version: '3'
services:
  chremoas-ng:
    image: ko.local/chremoas-ng:49ee47d24f54cd9f519b7918ae87b94938a3c6f74b27ba0719324727c8f39c30
    restart: always
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      CONSUL: 10.42.1.30:8500
      CONFIG_NAMESPACE: chremoas-dev

