version: '3'
services:
  chremoas-ng:
    image: docker.io/chremoas/chremoas-ng@sha256:1b7a7b9b6bea4b14b6c428a47ea2d78fd2e8c985a9956607abfd73866bddbfbe
    restart: always
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      CONSUL: 10.42.1.30:8500
      CONFIG_NAMESPACE: chremoas-dev

---
