version: '3'
services:
  chremoas-ng:
    image: docker.io/chremoas/chremoas-ng@sha256:abc9dd0fde5a34edc0c3baf3e1ba1b05760d7fc57e4083171ee58c15264a4a62
    restart: always
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      CONSUL: 10.42.1.30:8500
      CONFIG_NAMESPACE: chremoas-dev

---
