version: '3'
services:
  chremoas-ng:
    image: docker.io/chremoas/chremoas-ng@sha256:878da885bdbd0b7304904e9cb2d044a3f2273d434b34b52c626952fd32878a0e
    restart: always
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      CONSUL: 10.42.1.30:8500
      CONFIG_NAMESPACE: chremoas-dev

---
