version: '3'
services:
  chremoas-ng:
    image: docker.io/chremoas/chremoas-ng@sha256:65d4ad543a916149cde2f26bbafec83eb3f4f3959422d9a4d2828aafe41acebb
    restart: always
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      CONSUL: 10.42.1.30:8500
      CONFIG_NAMESPACE: chremoas-dev

---
