version: '3'
services:
  chremoas-ng:
    image: docker.io/chremoas/chremoas-ng@sha256:d32933e7628ff9fbc04e8261b1b43568f448b3184f8f88c30bd3f33146435220
    restart: always
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      CONSUL: 10.42.1.30:8500
      CONFIG_NAMESPACE: chremoas-dev

---
