version: '3'
services:
  chremoas-ng:
    image: ko://github.com/chremoas/chremoas-ng
    restart: always
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      CONSUL: 10.42.1.30:8500
      CONFIG_NAMESPACE: chremoas-dev
