style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/chremoas/chremoas-ng
options:
  commits:
    filters:
      Type:
        - fix
        - feat
        - chore
  commit_groups:
    title_maps:
      fix: 🐞 Fix
      feat: 💫 Feature
      chore: 🧹 Chore
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  refs:
    actions:
      - Closes
      - Fixes
  notes:
    keywords:
      - "BREAKING"